---
title: "bsi_geo_state"
author: "Rachel Landers"
date: "9/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
bsi <- readxl::read_excel(here::here("data", "prepped", "bsi_geo_state.xlsx"))
```
```{r}
tail(bsi)
```
```{r}
summary(bsi)
```

```{r}
current_bsi <- bsi %>% 
  subset(date == '2019-8')
```
```{r}
summary(current_bsi, na.rm = TRUE)
```
```{r}
ggplot(current_bsi, aes(bsi)) +
  geom_histogram(bins = 10, color = "white")
```

```{r}
current_bsi_geo_data <- current_bsi %>%
  inner_join(map_data("state"), by = c("RegionName" = "region"))
head(current_bsi_geo_data)
```

```{r}
current_bsi_map <- ggplot() +
    geom_polygon(data = map_data("state"), 
                 aes(x = long, 
                     y = lat, 
                     group = group), 
                 color = "black", 
                 fill ="blue") +
    geom_polygon(data = current_bsi_geo_data, 
             aes(x = long, 
                 y = lat,
                 fill = bsi,
                 group = group),
             color = "white") +
    scale_fill_gradient(low = "black", high = "red") +
  theme_minimal()
print(current_bsi_map)
ggsave("./bsi_map.jpeg")
```

