---
title: "Untitled"
author: "Rachel Landers"
date: "9/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dbplyr)
library(magrittr)
library(zipcode)
library(gganimate)
library(transformr)
data(zipcode)
zipcode
```
```{r define us}
us <- map_data('county')
head(us, 20)
```
```{r read in zillow bsi data}
bsi_per_county <- readxl::read_excel("../data/prepped/bsi_cross_geo_county.xlsx")
head(bsi_per_county)
```
```{r}
bsi_per_county %>% 
  distinct(year_mon) %>% 
  arrange(desc(year_mon))
```

```{r merge data}
bsi_geographical_data <- bsi_per_county %>% 
  subset(year_mon == '2019-7') %>% 
  inner_join(us)
head(bsi_geographical_data)
```

```{r}
bsi_plot  <- ggplot() +
geom_polygon(data = map_data("county"), 
             aes(x = long, 
                 y = lat, 
                 group = group)) +
  coord_quickmap() +
  geom_point(data = bsi_geographical_data, 
             aes(x = long, 
                 y = lat,
                 color = bsi)) 
print(bsi_plot)
```
```{r}
county_map <- map_data("county")
bsi_map <- ggplot() +
    geom_polygon(data = county_map, 
                 aes(x = long, 
                     y = lat, 
                     group = group), 
                 color = "white", 
                 fill ="gray") +
    geom_polygon(data = bsi_geographical_data, 
             aes(x = long, 
                 y = lat,
                 fill = bsi,
                 group = group),
             color = "white") +
    scale_fill_gradient(low = "blue", high = "red")
print(bsi_map)
```

is `map_data(usa)` a reliable data source?
trouble with merging?
preference for libraries?

```{r}
states <- map_data("county")
head(states)
ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, group = group), color = "gray", fill = "white",) + 
  coord_fixed(1.3) +
  guides(fill=FALSE)
```
```{r read in zillow bsi data}
bsi_per_county <- readxl::read_excel(here::here("data", "prepped", "bsi_cross_geo_county.xlsx"))
head(bsi_per_county)
```
```{r}
county_data <- map_data("county")
bsi_per_county_geo_location <- bsi_per_county %>% 
  inner_join(county_data)
```

```{r}
bsi_map <- ggplot(bsi_per_county_geo_location, aes(long, lat)) +
  geom_polygon(fill = "purple")

  
      # geom_polygon(data = county_map, 
    #              aes(x = long, 
    #                  y = lat, 
    #                  group = group), 
    #              color = "white", 
    #              fill ="gray") +
    # geom_polygon(data = bsi_geographical_data, 
    #          aes(x = long, 
    #              y = lat,
    #              fill = bsi,
    #              group = group),
    #          color = "white") +
    # scale_fill_gradient(low = "blue", high = "red")
print(bsi_map)
```

```{r}
p1 <- ggplot(data = bsi_per_county_geo_location, 
             aes(x = long, y = lat, group = 1)) +
  geom_polygon(aes(fill = bsi)) 
print(p1)
p1 +
  transition_states(year_mon,
                    transition_length = 2,
                    state_length = 1)
```

